version: 0.1

phases:
  pre_build:
    runtime-versions:
      python: 3.7
    commands:
      - echo deploying `date`
  build:
    commands:
      - echo deploying static content to s3
      - aws s3 sync . s3://sweet-n-sour.craiggunson.com --acl public-read --cache-control "max-age=60"  --delete
      
  post_build:
    commands:
      - echo build completed on `date`